losnoco/Cog

- Cog.xcodeproj/project.pbxproj
I couldn’t build until I removed this entry.
> Remove DevelopmentTeam that slipped through.

- Frameworks/lazyusf2/lazyusf2/r4300/recomp.c
If compiled with the macOS 10.14 SDK, MAP_JIT will be defined and passed as a flag to mmap to allocate memory for the dynarec, but passing this flag will cause mmap to fail if running on macOS 10.13 and below; on macOS check the OS version at runtime, set and cache the appropriate flags for mmap.
Fixes #47
> Avoid using MAP_JIT mmap flag on macOS < 10.14

- Base.lproj/MainMenu.xib
- Window/VolumeButton.m
- Window/VolumeSlider.h
- Window/VolumeSlider.m
Also fixes cut off Knob of Slider knob on Big Sur.
https://user-images.githubusercontent.com/8330119/103849168-182f7c80-50b5-11eb-8d5d-39c7bd3cf360.mov
> Update volume slider to use NSPopover.

- Application/PlaybackEventController.m
- Preferences/General/Base.lproj/Preferences.xib
- Preferences/General/GeneralPreferencesPlugin.h
- Preferences/General/GeneralPreferencesPlugin.m
Also hide no-op iTunes Style option.
> Show album art with UserNotification api.

- Window/VolumeButton.h
- Window/VolumeButton.m
- Window/VolumeSlider.m
Fixes #35 
Also added Haptic Feedback, when dragging volume slider with Magic Trackpad/Touchpad
> Show Volume slider in NSPopover instead of CGWindow.

- Window/VolumeButton.m
> Fix Volume Slider popover reattaching to window.

- Preferences/General/Base.lproj/Preferences.xib
- Preferences/General/GeneralPreferencePane.h
- Preferences/General/GeneralPreferencePane.m
- Preferences/General/GeneralPreferencesPlugin.h
- Preferences/General/GeneralPreferencesPlugin.m
- Preferences/General/HotKeyPane.m
- Preferences/General/MIDIPane.m
- Preferences/General/OutputPane.m
- Preferences/PreferencePanePlugin.h
- Preferences/PreferencesController.m
- Preferences/PreferencesWindow.h
- Preferences/PreferencesWindow.m
And refactoring of Preference Window.
> Use SF Symbols in Preferences on Big Sur.

- Application/AppController.m
- Base.lproj/MainMenu.xib
- Window/MiniWindow.m
Fix deprecation warnings.
Set max and min size for content view in code.
> Revamp Mini Window shortcuts.

- Base.lproj/InfoInspector.xib
- InfoInspector/InfoWindowController.m
> Align Info Inspector with app's MainWindow.

- Application/AppController.m
As per https://stackoverflow.com/questions/6562303/nsstring-lookup-in-nsset#comment9492803_6563936 this should work as expected.
Reason: I just thought this is a better way 😄
> Use NSSet for broken feed URL lookup.

- Base.lproj/MainMenu.xib
- Window/PositionSlider.h
- Window/PositionSlider.m
- Window/TimeField.h
- Window/TimeField.m
> Fix Status bar message v-alignment and use monospaced font for Time.

- .github/workflows/debug.yml
We only need to check if changes are buildable.
> Do not use signing capabilities in GitHub Actions build.

- Window/VolumeSlider.m
> Scale VolumeSlider linearly if volume is limited.

- Visualization/SpectrumView.m
https://user-images.githubusercontent.com/8330119/169720301-4b753f96-a853-4569-9318-294209624082.mov
> [Visualizer] Adjust 2d projection camera angles.

- Window/AboutWindowController.swift
Allow opening links in default browser
Close window on Esc
Add rounded corners
> AboutWindow adjustments

- Preferences/Preferences/GeneralPane.m
- Preferences/Preferences/PathSuggester.xib
Added a title to the window, make the table view resize properly, and
remove the font size inheritance from the main window.
Signed-off-by: Kevin López Brante <kevin@kddlb.cl>
> [Sandbox] Fixed path suggester window

- Base.lproj/Equalizer.xib
- Base.lproj/InfoInspector.xib
- Base.lproj/MainMenu.xib
- Base.lproj/OpenURLPanel.xib
- Base.lproj/SpotlightPanel.xib
- Cog.xcodeproj/project.pbxproj
- Playlist/PlaylistController.m
- Preferences/Preferences/Base.lproj/PathSuggester.xib
- Preferences/Preferences/Base.lproj/Preferences.xib
- Preferences/Preferences/en.lproj/Localizable.strings
- Preferences/Preferences/es.lproj/InfoPlist.strings
- Preferences/Preferences/es.lproj/Localizable.strings
- Preferences/Preferences/es.lproj/Preferences.strings
- Transformers/TotalTimeTransformer.m
- en.lproj/Localizable.strings
- en.lproj/Localizable.stringsdict
- es.lproj/AboutWindowController.strings
- es.lproj/Credits.html
- es.lproj/Equalizer.strings
- es.lproj/Feedback.strings
- es.lproj/FileTree.strings
- es.lproj/InfoInspector.strings
- es.lproj/InfoPlist.strings
- es.lproj/Localizable.strings
- es.lproj/Localizable.stringsdict
- es.lproj/MainMenu.strings
- es.lproj/OpenURLPanel.strings
- es.lproj/SpectrumWindow.strings
- es.lproj/SpotlightPanel.strings
- Plugs the Total duration text to macOS's localization technology
- Adds a proper Spanish translation
- Adapts certain dialogs to make them more suitable for translation
> [Translation] The Big Translation Commit

- Application/AppController.m
- Plugins/AdPlug/AdPlug.xcodeproj/project.pbxproj
- Plugins/AdPlug/AdPlug/AdPlugDecoder.h
- Plugins/AdPlug/AdPlug/AdPlugDecoder.mm
- Plugins/GME/GameDecoder.h
- Plugins/GME/GameDecoder.m
- Plugins/HighlyComplete/HighlyComplete/HCDecoder.mm
- Plugins/Hively/Hively/HVLDecoder.h
- Plugins/Hively/Hively/HVLDecoder.m
- Plugins/MIDI/MIDI/MIDIDecoder.h
- Plugins/MIDI/MIDI/MIDIDecoder.mm
- Plugins/OpenMPT/OpenMPT.xcodeproj/project.pbxproj
- Plugins/OpenMPT/OpenMPT/OMPTDecoder.h
- Plugins/OpenMPT/OpenMPT/OMPTDecoder.mm
- Plugins/libvgmPlayer/libvgmDecoder.h
- Plugins/libvgmPlayer/libvgmDecoder.mm
- Plugins/sidplay/SidDecoder.h
- Plugins/sidplay/SidDecoder.mm
- Plugins/sidplay/sidplay.xcodeproj/project.pbxproj
- Plugins/vgmstream/vgmstream/VGMDecoder.h
- Plugins/vgmstream/vgmstream/VGMDecoder.m
- Preferences/Preferences/Base.lproj/Preferences.xib
- Preferences/Preferences/GeneralPreferencesPlugin.m
- Preferences/Preferences/Preferences.xcodeproj/project.pbxproj
- Preferences/Preferences/TimeIntervalToStringTransformer.h
- Preferences/Preferences/TimeIntervalToStringTransformer.m
- Preferences/Preferences/en.lproj/Preferences.strings
- Preferences/Preferences/es.lproj/Preferences.strings
Merging this now that the translation is in.
> Synth settings

- Application/AppController.m
- Preferences/Preferences/Base.lproj/Preferences.xib
- Visualization/SpectrumViewSK.m
Also it should be good to add pref observation and recreate views when pref is changed.
> Add preference to choose between SceneKit and DDB spectrum.

- pl.lproj/AboutWindowController.strings
- pl.lproj/Credits.html
- pl.lproj/Equalizer.strings
- pl.lproj/Feedback.strings
- pl.lproj/FileTree.strings
- pl.lproj/InfoInspector.strings
- pl.lproj/InfoPlist.strings
- pl.lproj/Localizable.strings
- pl.lproj/Localizable.stringsdict
- pl.lproj/MainMenu.strings
- pl.lproj/OpenURLPanel.strings
- pl.lproj/SpectrumWindow.strings
- pl.lproj/SpotlightPanel.strings
It is not full translation, but at least some stuff will come in Polish.
> Polish translation

- pl.lproj/Equalizer.strings
- pl.lproj/FileTree.strings
- pl.lproj/Localizable.strings
Hi again.
My translation is getting ready, just only few files and strings are not translated.
Have a good day.
> next Polish translations, next strings translated.
